# Generated by Django 6.1 on 2026-08-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
